swagger: "2.0"
info:
  title: Coronatime API
  description: Here goes description
  version: 0.1.9

host: 127.0.0.1
basePath: /api/v1

paths:
  /sellers/send_verification_code:
    post:
      summary: send verification code.
      consumes:
        - application/json
      parameters:
        - in: body
          name: mobile
          description: The user to create.
          schema:
            type: object
            required:
              - mobile
            properties:
              mobile:
                type: string
                default: "09391121001"

      responses:
        200:
          description: A User object.
          schema:
            type: object
            properties:
              data:
                type: object
                default: { "code": "1234" }

  /sellers/enter_verification_code:
    post:
      summary: enter verification code.
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: The user to create.
          schema:
            type: object
            required:
              - mobile
              - code
            properties:
              mobile:
                type: string
                default: "09391121001"
              code:
                type: integer

      responses:
        200:
          description: A User object.
          schema:
            type: object
            properties:
              data:
                type: object
                default: { "code": "1234" }

  /sellers/password:
    post:
      summary: enter verification code.
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: The user to create.
          schema:
            type: object
            required:
              - password
              - password_confirmation
            properties:
              password:
                type: string
              password_confirmation:
                type: string

      responses:
        200:
          description: A User object.
          schema:
            type: object
            properties:
              data:
                type: object
                default: { "code": "1234" }
