openapi: 3.0.0
info:
  title: prize wheel
  description: ''
  version: 0.1.9


servers:
  - url: api/v1/sellers

paths:
  /send_verification_code:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile:
                  type: string
                  default: "09391121001"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                default: { "code": "1234" }

  /enter_verification_code:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile:
                  type: string
                  default: "09391121001"
                code:
                  type: string

      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                default: { "code": "1234" }

  /password:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  default: "123456"
                password_confirmation:
                  type: string
                  default: "123456"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                default: { "message": "login", "data": [] }

  /login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                mobile:
                  type: string
                  default: "09391121001"
                password:
                  type: string
                  default: "123456"
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                default: { "message": "login", "data": [] }
